### ISSUE TITLE
Uncaught NPE when sent an empty websocket message with auth

### ISSUE THREAD

**Issue by jiekang** [rh-jmc-team/container-jfr#109]
Using websockat to connect to ws://localhost:8181/command if I press enter, inputting an empty string (I assume), there is an uncaught exception that makes the Websocket stuff die and no further action can be taken without restarting the server.
```
Exception in thread "main" java.lang.NullPointerException
        at com.redhat.rhjmc.containerjfr.tui.ws.WsCommandExecutor.run(WsCommandExecutor.java:50)
        at com.redhat.rhjmc.containerjfr.ContainerJfr.main(ContainerJfr.java:69)
```

If incorrect input like "hi" is provided, the server continues after responding over the websocket with error details. That should also occur for an empty message.

**Comment by andrewazores** [comment]
Neat. Seems like it's this bug: https://github.com/google/gson/issues/457

**Comment by jiekang** [comment]
Huh cool
