### ISSUE TITLE
`list` command is missing some information

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#160]
The `list` command is missing some useful information. When executed in "serialized" form, ie when ContainerJFR is in WebSocket execution mode, the output includes the download URL of the recording but not the report URL. When running in non-serialized, interactive mode (ie. interactive shell execution mode), neither download or report URLs are included in the printed output.

Steps to reproduce:

(interactive)
```
$ mvn clean package
$ sh run.sh -it
- connect localhost
> dump foo 30 template=Continuous
> list
```

(serialized)
```
$ mvn clean package
$ sh run.sh
$ websocat ws://localhost:8181/api/v1/command # in another terminal
{command:dump,args:[foo,30,"template=Continuous"]}
{command:list}
```

**Comment by andrewazores** [comment]
The connectionless API PR has just been merged, so the `connect` command no longer exists. The ID of the target now needs to be passed to the `list` command:



(interactive)
```
$ mvn clean package
$ sh run.sh -it
> dump localhost foo 30 template=Continuous
> list localhost
```
(serialized)
```
$ mvn clean package
$ sh run.sh
$ websocat ws://localhost:8181/api/v1/command # in another terminal
{command:dump,args:[localhost, foo,30,"template=Continuous"]}
{command:list, args:[localhost]}
```

**Comment by vic-ma** [comment]
Two notes:
* container-jfr was looking for container-jfr-core version 0.12.3, so I ended up installing your fork of core, which seems to work
* The serialized version of the command already includes the report URL (not just the download URL), so  the only change I made was to add the two URLs to the interactive mode

And one question:
* I have the change working now, and it doesn't break any existing tests; should I add a new test to check the URLs for the interactive mode?—the serialized version does have a check for its URLs, so I'm thinking it probably makes sense to have one for the interactive version too?

**Comment by andrewazores** [comment]
> container-jfr was looking for container-jfr-core version 0.12.3, so I ended up installing your fork of core, which seems to work

Ah whoops, I had made the commits to cut that version release locally and didn't push them upstream. I've gone ahead and done that now, so upstream and my fork should be identical again.

> I have the change working now, and it doesn't break any existing tests; should I add a new test to check the URLs for the interactive mode?—the serialized version does have a check for its URLs, so I'm thinking it probably makes sense to have one for the interactive version too?

Yes, it definitely makes sense to add these new tests. Please do, and open your PR when ready!
