### ISSUE TITLE
Tab-Separated Output in Terminal Should be Properly Aligned

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr#169]
Some commands that are run in interactive mode format their output using tabs. In the code, this is done by using a constant amount of tabs for each print statement.  Due to the variable length of the first value, this can sometimes result in a misaligned output.

If the first value is too short, it may need more tabs, and if the first value is too long, it may need less tabs, than the preset amount. Any fix will also need to change the affected commands' tests, since they expect the output to have the preset amount of tabs currently used.

Examples:
```
>search-events localhost compiler

"search-events" "[localhost, compiler]"
[TRACE] Locking connection localhost:9091
	jdk.Compilation	options: [enabled, threshold]
	jdk.CompilerPhase	options: [enabled, threshold]
	jdk.CompilationFailure	options: [enabled]
	jdk.CompilerInlining	options: [enabled]
	jdk.CompilerStatistics	options: [enabled, period]
	jdk.CompilerConfiguration	options: [enabled, period]
[TRACE] Unlocking connection localhost:9091
> list localhost

"list" "[localhost]"
[TRACE] Locking connection localhost:9091
Available recordings:
	getName		foo
	getId		1
	getState		STOPPED
	getDuration		5000
	isContinuous		false
	getToDisk		true
	getStartTime		1591024248950
	getMaxAge		0
	getMaxSize		0
	getDownloadUrl		http://0.0.0.0:8181/api/v1/targets/service:jmx:rmi:%2F%2F%2Fjndi%2Frmi:%2F%2Flocalhost:9091%2Fjmxrmi/recordings/foo
	getReportUrl		http://0.0.0.0:8181/api/v1/targets/service:jmx:rmi:%2F%2F%2Fjndi%2Frmi:%2F%2Flocalhost:9091%2Fjmxrmi/reports/foo

[TRACE] Unlocking connection localhost:9091
```

**Comment by andrewazores** [comment]
Here are some links to how something similar was implemented in the original Thermostat cli client:

https://icedtea.classpath.org/hg/thermostat/file/77b119517732/common/core/src/main/java/com/redhat/thermostat/common/cli/TableRenderer.java

https://icedtea.classpath.org/hg/thermostat/file/77b119517732/client/cli/src/main/java/com/redhat/thermostat/client/cli/internal/ListVMsCommand.java

**Comment by vic-ma** [comment]
Closing this, since the interactive mode is only used in development and may be removed soon anyway, so the large changes needed for this don't make sense.
