### ISSUE TITLE
Cannot build due a missing dependenc

### ISSUE THREAD

**Issue by jerrinot** [rh-jmc-team/container-jfr#180]
Hi,

I tried to build this project and it's failing with:
```
[ERROR] Failed to execute goal on project container-jfr: Could not resolve dependencies for project com.redhat.rhjmc.containerjfr:container-jfr:jar:0.19.0: Could not find artifact com.redhat.rhjmc:containerjfr-core:jar:0.12.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

my steps to build it:
```
 1032  MAVEN_OPTS="-Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
 1033  mvn clean prepare-package exec:java
```

**Comment by andrewazores** [comment]
You must build `container-jfr-core` into your local Maven repository, as explained in the README:
https://github.com/rh-jmc-team/container-jfr#build .

Clone `container-jfr-core` and do a `mvn install` within it. This will also require that you have built a JMC 7.0.0-SNAPSHOT into your local Maven repository first.

**Comment by andrewazores** [comment]
Closing as invalid, unless we can get some more details and confirm that something really is broken. Everything appears to be as normal from here though.
