### ISSUE TITLE
PlatformClients should report JMX Service URLs

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#183]
Currently, some PlatformClients' discovery mechanisms return lists containing JMX Service URLs, and others return `host:port` pairs. Both of these are acceptable in the various APIs requiring a targetID, however the `host:port` pairs should only really be expected to be used in users' hand-written requests, ie in development/debugging/testing as a shorthand. API responses should uniformly contain JMX Service URLs to eliminate ambiguity.

This also means that the ServiceRef type would no longer need its `port` field, only the connection URL and an optional display alias.

**Comment by Alexjsenn** [comment]
I looked into removing the port field, but there are a few places where Im not sure if the behaviour is appropriate. For example, in scanTargets it would only give the ULR and not the port, is this acceptable?

**Comment by andrewazores** [comment]
A JMX Service URL should already include the port number, so yes.

**Comment by andrewazores** [comment]
Fixed in #215
