### ISSUE TITLE
build-images.sh fails integration tests

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#202]
https://github.com/rh-jmc-team/container-jfr-web/pull/98#issuecomment-653663216

The `build-images.sh` script tries to build both a minimal and a full-featured container image and runs the full unit- and integration-test suite against both. Integration testing against a minimal image currently fails, because there is an integration test that performs a basic check of the web-client index.html contents - which is not present in a minimal image at all.

There should be a way to configure integration tests so that some can be disabled when testing a minimal image, and the `build-images.sh` script should use this configuration to ensure only relevant tests are run.

**Comment by Alexjsenn** [comment]
I just looked into the errors, and it seems it passes all surefire and failsafe tests when it does the minimal build, its actually failing when running the full build. I tried looking into why it would fail but I can't seem to figure it out.

**Comment by andrewazores** [comment]
Can you post the logs of the failing build?

**Comment by Alexjsenn** [comment]
[build-images.txt](https://github.com/rh-jmc-team/container-jfr/files/4904595/build-images.txt)

**Comment by andrewazores** [comment]
Huh. Very strange. I can't reproduce this on my machine, so I'll see if I can set up another environment and try it there. I don't know why that integration test would be failing for the full-fledged image but passing for the minimal one, though.

**Comment by andrewazores** [comment]
Did this occur with a completely clean `container-jfr` repo, including the `web-client` submodule?

**Comment by Alexjsenn** [comment]
Yeah, even after trying in a new repo it still fails. I belive it has to do with the minify feature, which removes the tag that the test is looking for.

**Comment by andrewazores** [comment]
Yea. Just weird that my build has never reproduced it until just now, when I checked out a later version of the `web-client` submodule. I think the test fix we discussed is probably still appropriate.

**Comment by andrewazores** [comment]
@Alexjsenn can you check if this is still relevant?

**Comment by Alexjsenn** [comment]
Not any more!
