### ISSUE TITLE
`upload-recording` Hangs When Datasource URL is Invalid

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr#217]
If the URL points to a non-existent server, it will hang:
```
{command:upload-recording,args:[localhost,foo,"http://abc"]}
```

Also if the URL points to an existent but invalid server, it will hang (or it will throw a NPE; see #218):
```
{command:upload-recording,args:[localhost,foo,"http://localhost"]}
```

The command is working in 139649d, which is the first commit after the Connectionless API where `upload-recording` was working:

```
{command:upload-recording,args:[localhost,foo,"http://abc"]}    
{"id":null,"commandName":"upload-recording","status":-2,"payload":"UnknownHostException: abc: Name or service not known"}

{command:upload-recording,args:[localhost,foo,"http://localhost"]}
{"id":null,"commandName":"upload-recording","status":-2,"payload":"HttpHostConnectException: Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)"}
```

**Comment by vic-ma** [comment]
@andrewazores 

If I do this:
```
try {
    HttpRequest<Buffer> request = webClient.postAbs(datasourceUrl);
    
    System.out.println("POSTABS SUCCEEDED");  /* DEBUG */

    request.sendMultipartForm(
            form,
            uploadHandler -> {

                System.out.println("INSIDE HANDLER");  /* DEBUG */

                if (uploadHandler.failed()) {
                    future.completeExceptionally(uploadHandler.cause());
                    return;
                }
                HttpResponse<Buffer> response = uploadHandler.result();
                future.complete(
                        new ResponseMessage(
                                response.statusCode(),
                                response.statusMessage(),
                                response.bodyAsString()));
            });
    ...
```

The output will just be "POSTABS SUCCEEDED", without "INSIDE HANDLER", so it looks like the hanging is happening right after the request is sent, I guess because it waits indefinitely for a response. So I think we just need to add a timer to the request? And I guess the Apache HTTP client must have built-in functionality to recognize bad URLs/servers when it sends its requests, and vertx doesn't?

**Comment by andrewazores** [comment]
Yea, I'm not really sure about how/why Apache apparently handled this case and Vertx doesn't. I think all you need to do to test adding a request timeout is like this: `request.timeout(10_000L).sendMultipartForm(...)` (10 seconds of timeout).

FWIW I also have an HTTP Handler version of this command (two actually - one for saved and one for archived recordings) coming soon in a PR, so we'll have to check there as well and probably apply the same fix across all these similar implementations.

**Comment by andrewazores** [comment]
See #222

**Comment by vic-ma** [comment]
Hmm...adding the timeout didn't seem to fix it, and the handler doesn't even get run either. Running with a valid datasource URL still works.

I also tried making the timeout 1 ms, which should mean all URLs throw an exception. But in this case it just makes it so that a valid datasource URL hangs as well; the handler also isn't run.

```
         try {
             webClient
                     .postAbs(datasourceUrl)
+                    .timeout(1)
                     .sendMultipartForm(
                             form,
                             uploadHandler -> {
+                                System.out.println("INSIDE HANDLER");
                                 if (uploadHandler.failed()) {
                                     future.completeExceptionally(uploadHandler.cause());
                                     return;
```

I'm not sure what I can try now. I feel like this should have worked or at least the handler should have run.

**Comment by andrewazores** [comment]
That's very strange that even a valid datasource URL doesn't trip the handler when it times out.

With that hunch in mind, here's a similar-sounding StackOverflow answer I found:

https://stackoverflow.com/questions/35680924/how-to-solve-vertx-blocking-dns-issue

Setting `-Dvertx.disableDnsResolver` on the ContainerJFR JVM (or alternatively, simply using `System.setProperty()` early enough) would be an interesting next step to test and experiment with.

There is also this:

https://stackoverflow.com/questions/47049669/vertx-httpclient-does-not-timeout

Perhaps we need to use `.setConnectTimeout()` or one of the various other timeouts.

**Comment by vic-ma** [comment]
I added `-Dvertx.disableDnsResolver` to `MAVEN_OPTS` but it didn't seem to change anything.

What I did find, however, is that if I change the HTTP request to a simple POST request without the file upload, Vertx correctly handles bad servers:

```
/* GRAFANA_DATASOURCE_URL=http://abc */

{"id":null,"commandName":"upload-recording","status":-2,"payload":"ExecutionException: java.net.UnknownHostException: failed to resolve 'abc' after 3 queries "}
```

Which makes much more sense than Vertx just not handling simple stuff like that.

I can't figure out what might be wrong with our file upload though. I tried changing the `MultipartForm` to a local text file upload to see if that would change things, but it still hanged. I also tried changing the `postAbs()` to `post("http://abc")`, but that also made no difference.

Or I guess maybe it could be that Vertx just doesn't recognize bad servers when uploading, but that doesn't seem likely. Especially since there is that weird behaviour of hanging with 1ms timeout, which makes it seems more like something is probably wrong.

**Comment by vic-ma** [comment]
Hmm adding `setConnectTimeout()` didn't seem to do anything. Even if I make it 1 ms, the correct URL still functions normally, and `http://abc` still hangs. But when I set the URL to `http://google.com`, it also hangs, which is strange.

If I change the POST to non-uploading, `http://abc` "fails to resolve after 3 tries." A valid jfr-datasource just gives a 404, I guess because we're using the upload URL without providing a file to upload, though it's strange that it can do this with a 1 ms timeout. Setting the URL to Google gives what I think is the expected timeout exception:
```
{"id":null,"commandName":"upload-recording","status":-2,"payload":"ExecutionException: io.netty.channel.ConnectTimeoutException: connection timed out: google.com/172.217.164.206:80"}
```

Unassigning myself for now since it's not clear what the fix for this is.

**Comment by andrewazores** [comment]
Very strange.

I think the worst-case scenario is to "fix" it by first checking the health status of the datasource (`GET /`), and if that succeeds then continue on to attempt the `POST`. This adds a roundtrip of latency, and there is also the narrow possibility that the datasource goes away between the successful `GET` and the `POST` attempt, but it's better than just hanging.

**Comment by vic-ma** [comment]
I have a `GET`-check fix working. I'm going to try to do some more testing for this bug first, but if nothing works I can write tests for the `GET`-check and open a PR.
