### ISSUE TITLE
`upload-recording` Sometimes Causes CJFR to Hang

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr#219]
If you run `upload-recording` on the same recording multiple times, it will eventually cause CJFR to hang. I'm still not totally sure how the speed at which you run the commands affects the bug. Once I ran the commands 1-2 seconds apart and was still able to cause the hang. For replicating the bug, spamming the commands is fastest.

I discovered this bug in the web client, but since I was also able to replicate the bug with a slow speed in the backend, I think this bug is unrelated to the web client.

```
{command:dump,args:[localhost,foo,3,"template=Continuous"]}
{"id":null,"commandName":"dump","status":0,"payload":null}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 15334564489196067905.tmp\nSet: 15334564489196067905.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 2781532471906468424.tmp\nSet: 2781532471906468424.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 8537316693928713982.tmp\nSet: 8537316693928713982.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 10557930756227151177.tmp\nSet: 10557930756227151177.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 1204474703124060677.tmp\nSet: 1204474703124060677.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 18216638194210754985.tmp\nSet: 18216638194210754985.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 5965971226875301402.tmp\nSet: 5965971226875301402.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 18007282340530354950.tmp\nSet: 18007282340530354950.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 15627559220938308910.tmp\nSet: 15627559220938308910.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 8779513082014679025.tmp\nSet: 8779513082014679025.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 2655584385347008712.tmp\nSet: 2655584385347008712.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 11250004617185706784.tmp\nSet: 11250004617185706784.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 11266580438287255899.tmp\nSet: 11266580438287255899.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{"id":null,"commandName":"upload-recording","status":0,"payload":{"status":"200 OK","body":"Uploaded: 12734493064920028414.tmp\nSet: 12734493064920028414.tmp\n"}}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}
{command:upload-recording,args:[localhost,foo,"http://localhost:8080/load"]}

(hangs)
```
Here is `jfr-datasource/file-uploads/`; you can see the `.tmp` files for all the uploads that succeeded, and the one weirdly-named file without an extension for the upload that caused the hanging; the file contents look similar though:
```
10387362588480962673.tmp  15155514639766042110.tmp  2827858244711833760.tmp  7184447614406793836.tmp
10536061078443041110.tmp  16917413980982922340.tmp  3769165150256075679.tmp  7266179292868855410.tmp
11373525827043631953.tmp  17211686932408156581.tmp  3995818126536051967.tmp  7864242991763668155.tmp
12394492395577763325.tmp  17246354730127816606.tmp  4856998670114603973.tmp  8147293106808081124.tmp
12701601026652612097.tmp  17254282617397912418.tmp  5145152727224741018.tmp  8230064677676318942.tmp
12967194330429686684.tmp  17820005885949568433.tmp  5269404510903904986.tmp  8801551624989653817.tmp
13151946802868327731.tmp  2180702792384647872.tmp   6061525503557380697.tmp  9447051738769902512.tmp
14339721896709958700.tmp  2297921317514357984.tmp   6188350952693487752.tmp  f708c131-92da-472a-a640-9b94e06502ab
14631486803999565588.tmp  2668852330861664868.tmp   6396986415646809227.tmp
14850639599432227238.tmp  281187754993163740.tmp    6700971946932294198.tmp
```

Is it also intended that the names for the uploaded recordings are like this now? Since previously if I uploaded `foo`, it would show up in `file-uploads/` as `foo`. And if I uploaded `foo` again, then it would be named something like `545fd044-a502-4eb9-80a4-028370e61a7d-foo`.

In 139649d, I was not able to reproduce this bug, so at least that gives us a good start for tracking this down.

Possibly related: #217, #218.

**Comment by andrewazores** [comment]
The contents of `file-uploads` aren't part of any API, so the filenames of its contents don't necessarily mean anything. I don't think the datasource itself cares what the names of the files are, either. The names like `9447051738769902512.tmp` look like they're probably coming from this snippet of the current ContainerJFR upload implementation:

```
        if (currentRecording.isPresent()) {
            // FIXME extract createTempFile wrapper into FileSystem
            Path tempFile = Files.createTempFile(null, null);
            return Optional.of(
                    targetConnectionManager.executeConnectedTask(
                            targetId,
                            connection -> {
                                InputStream stream =
                                        connection
                                                .getService()
                                                .openStream(currentRecording.get(), false);
                                try (stream) {
                                    fs.copy(stream, tempFile, StandardCopyOption.REPLACE_EXISTING);
                                }
                                return Pair.of(tempFile, true);
                            }));
        }
```

ie, the recording stream is read out from the target JVM and written into a temp file with a randomly-generated name, then the target connection is closed and that temp file is what is uploaded to the datasource. Previously the transfer was done streaming with no temp file, ie the target connection was opened, then the recording stream was opened, and its contents were read and immediately written to the datasource upload stream, and then the streams and connection were all closed. It's unfortunate that this implementation regressed in this way, but it's not as clear how to implement the direct streaming using Vertx as opposed to Apache Http. The name of the uploaded file could be modified to match the name of the recording but I'm not sure that that actually matters. The name `545fd044-a502-4eb9-80a4-028370e61a7d-foo` looks like it might be from the datasource itself renaming the file to avoid the naming collision?

Maybe you could try attaching a debugger or at least adding a bunch of log statements to help trace the execution within ContainerJFR, then reproduce the bug and see where it gets to before hanging.

**Comment by vic-ma** [comment]
>It's unfortunate that this implementation regressed in this way, but it's not as clear how to implement the direct streaming using Vertx as opposed to Apache Http. The name of the uploaded file could be modified to match the name of the recording but I'm not sure that that actually matters.

Yeah, I don't think the names are an issue either. Just wanted to make sure that it's an expected change, and that my jfr-datasource wasn't messed up.

**Comment by vic-ma** [comment]
On the failed command run, the execution gets to the `future.get()` line, where it will start blocking, and the handler is never entered.

**Comment by andrewazores** [comment]
Same thing as #217 then, although seemingly sporadic?

**Comment by vic-ma** [comment]
Yeah, it seems like it. But in this case the `GET`-check doesn't fix the problem. Also tested just now and adding a timeout still doesn't work. And if I send multiple `GET /` requests, I do not run into the hanging.

**Comment by andrewazores** [comment]
It definitely seems to me that something is wrong with the Vert.x WebClient's POST handling then. If we can't find any other similar bug reports around then I think we should open one, at least to ask the question if maybe something is wrong with our setup.

**Comment by vic-ma** [comment]
Yeah, I've also tried getting rid of as many variables as possible by removing `WebClientOptions`, using a plaintext file upload, using `post()` instead of `postAbs()`, putting the code in `ListCommand` etc., all at once, but nothing seemed to change. I'll try to see if I can isolate the bug into a single file or something for a bug report. Maybe doing this will reveal more insight into the bug as well.

**Comment by vic-ma** [comment]
It looks like updating the Vertx version from `3.8.5` to `3.9.2` fixed both of the hanging bugs :|

`3.9.0` is enough to fix the `http://abc` one, but it takes `3.9.1` to fix the sporadic one.

Looking at the Vertx release notes, it seems like these are the relevant issues that were fixed:
[WebClient sendForm misses timeout failures](https://github.com/vert-x3/vertx-web/issues/1520)
[WebClient multipart upload can lose buffers ](https://github.com/vert-x3/vertx-web/issues/1609)

Now the only problem is that I'm not sure how much updating our Vertx version will cause stuff to break. Right now I see this one failed unit test, which I will try to investigate:
```
[ERROR] Failures: 
[ERROR]   CorsEnablingHandlerTest$HandlingTest.shouldRespond403ForCORSRequestWithInvalidOrigin:181 
Wanted but not invoked:
res.setStatusCode(403);
-> at com.redhat.rhjmc.containerjfr.net.web.handlers.CorsEnablingHandlerTest$HandlingTest.shouldRespond403ForCORSRequestWithInvalidOrigin(CorsEnablingHandlerTest.java:181)

However, there was exactly 1 interaction with this mock:
res.setStatusMessage(
    "CORS Rejected - Invalid origin"
);
-> at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:152)
```

**Comment by andrewazores** [comment]
Nice work digging that up. The `CorsEnablingHandler` just wraps around the Vertx `CorsHandler`, and that test was written against that class' actual behaviour, so it may have just changed between versions. The new status message makes sense, although I'm curious why that was (apparently) the only interaction with the mock - was no status code set? Responding with a `200 OK` and a CORS rejection message seems wrong. The rest of what we use from Vertx is pretty core functionality, so our odds of running into any more buggy corners cases are slim. I think once we sort out what the updated CorsHandler is doing we can probably go ahead and update our dependency version.

**Comment by andrewazores** [comment]
https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java

So it does still set a `403` code, just does it differently. Seems fine by me.

**Comment by andrewazores** [comment]
Looks like "Fixes x, y, z..." only closes the first issue automatically.
