### ISSUE TITLE
Errors Related to `HttpStatusException` When Running Unit Tests

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr#231]
I think I've had this for a while now:

In serial execution, so it's clear which tests caused the errors:
```
[INFO] Running com.redhat.rhjmc.containerjfr.net.web.handlers.ReportGetHandlerTest
io.vertx.ext.web.handler.impl.HttpStatusException: Not Found

[INFO] Running com.redhat.rhjmc.containerjfr.net.web.handlers.TargetRecordingGetHandlerTest
io.vertx.ext.web.handler.impl.HttpStatusException: Internal Server Error
Caused by: java.lang.NullPointerException
io.vertx.ext.web.handler.impl.HttpStatusException: Not Found
```

The errors don't cause the test run to fail, so I've never really thought much about them, but looking more closely I guess it probably does mean something is wrong. Am I missing a dependency maybe?

**Comment by andrewazores** [comment]
No, I don't think it's a missing dependency. That would more likely result in a compilation failure, and it's hard to image how you would be missing something anyway - Maven should be automatically downloading them for you before compiling, let alone running tests.

I think it's actually just a case of test debugging left around by mistake. Here's what `ReportGetHandlerTest` has to show:

```

    @Test
    void shouldRespond404IfRecordingNameNotFound() throws Exception {
        when(authManager.validateHttpHeader(Mockito.any()))
                .thenReturn(CompletableFuture.completedFuture(true));

        RoutingContext ctx = mock(RoutingContext.class);
        HttpServerRequest req = mock(HttpServerRequest.class);
        when(ctx.request()).thenReturn(req);

        when(ctx.pathParam("recordingName")).thenReturn("someRecording");
        when(reportService.get(Mockito.anyString())).thenReturn(Optional.empty());

        HttpStatusException ex =
                Assertions.assertThrows(HttpStatusException.class, () -> handler.handle(ctx));
        ex.printStackTrace();
        MatcherAssert.assertThat(ex.getStatusCode(), Matchers.equalTo(404));
    }
```

The exception is expected, but there is also an `ex.printStackTrace();` that was left there. That's probably what causes the `Not Found` message when that test runs, but it actually doesn't indicate a failure or anything wrong.
