### ISSUE TITLE
HTTP API documentation

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#240]
Documentation similar to `COMMANDS.md` should be created, outlining the HTTP API (any concrete class implementing `RequestHandler`). For each such handler the documentation should include:

- a brief synopsis of the purpose of the endpoint
- its HTTP method
- its path and an explanation of any path parameters
- a description of any query parameters, such as the expected format and whether they are required
- a description of any PUT/POST/PATCH request bodies (text format, file upload name, etc.)
- a description of the response body format
- descriptions of any response status codes other than `2xx`

Ideally, the documentation should be split into a main index document and a sub-document for specifically `API v1`, so that the document can be neatly extended later for `v2` and on.

This may initially be done by hand in some some human-readable markup format, but even better would be to implement this by using an API documentation generation tool. Here's one such tool: https://github.com/outofcoffee/vertx-oas

And even better would be to flip the script and define the API surface first, then generate implementation stubs from that, and finally fill in the existing implementations back into the stubs. Here's a document to help get started down that path: https://vertx.io/docs/vertx-web-api-contract/java/#_openapi_3. To create the API document, use a tool like [Swagger Editor](https://editor.swagger.io). However, this is probably a larger, later enhancement for a `v2+` API.

**Comment by vic-ma** [comment]
@andrewazores 

Mostly done now, just a couple of things I couldn't figure out myself:

1. The path for the health handler is just `/health`. I see that the PR for it is older than the other handlers, so should it have been updated to `/api/v1/health`?
2. Should I document the handlers that apply to all paths: `CorsEnablingHandler`, `CorsOptionsHandler`, `StaticAssetsGetHandler`, `WebClientAssetsGetHandler`? Since these feel more like they are things that go on in the background and are assumed than handlers that are specifically used?
3. I see that `AuthPostHandler` just returns a `200`. Is it used just as a simple check to see if the auth headers in the request are valid?

**Comment by andrewazores** [comment]
1. It could be. The other handlers under `/api/v1/*` paths generally have to do with the target JVMs, their flight recordings, and other associated data, whereas `/health` is about the container itself and its deployment. So on the one hand it makes some sense to have a distinction, but on the other hand the Health endpoint should probably also be versioned as well.
2. I think `StaticAssets`/`WebClientAssets` make sense to document as a wildcard so that it's clear what happens when a request is made to a path that isn't otherwise listed in the document. The `Cors` handlers probably don't need to be documented in terms of their routes and verbs, though.
3. Yea exactly. Its implementation is essentially just a no-op, with the real substance being handled by the abstract class that it extends.

**Comment by vic-ma** [comment]
>Yea exactly. Its implementation is essentially just a no-op, with the real substance being handled by the abstract class that it extends.

I'm a bit confused by how the auth header validation works. So I see that it goes into this method, which just ends up calling `auth.validateHttpHeader()`:
```
protected Future<Boolean> validateRequestAuthorization(HttpServerRequest req) throws Exception {
    return auth.validateHttpHeader(() -> req.getHeader(HttpHeaders.AUTHORIZATION));
}
```
But my understanding is that `AuthManager` is for user authentication, not JMX authentication, and authenticated handlers authenticate the JMX connection. So how come it's a method in `AuthManager` that is used to validate the header?

The problem I ran into is that with JMX auth enabled, but not user auth, `POST /api/v1/auth` always returned a `200` regardless of request headers, since the validation check just went to the `NoopAuthManager`.

>I think StaticAssets/WebClientAssets make sense to document as a wildcard so that it's clear what happens when a request is made to a path that isn't otherwise listed in the document.

Ah, I wasn't really sure what they are for, but I see now.

Both handlers are invoked when an invalid request is made, but I don't totally get how they work, so is there one I should use over the other in the doc to represent both? Is there one that is more like a "helper" handler and one that is more of a main handler?

And should I be able to see a webpage if I do `curl ... --output foo.html` and then `google-chrome foo.html`? I see that the output is a HTML file, but I just get a blank page when I open it in a browser. So I'm not really sure how I should describe the output in the doc. But it looks like it should be something like a simple page just saying "ContainerJFR"?

Is this the correct output?
```
<!doctype html><html lang="en-US"><head><meta charset="utf-8"><title>ContainerJFR</title><meta id="appName" name="application-name" content="ContainerJFR"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/png" href="https://www.patternfly.org/components/patternfly/dist/img/favicon.ico"><base href="/"><link href="app.css" rel="stylesheet"></head><body><noscript>Enabling JavaScript is required to run this app.</noscript><div id="root"></div><script src="app.bundle.js"></script></body></html>
```

**Comment by andrewazores** [comment]
> > Yea exactly. Its implementation is essentially just a no-op, with the real substance being handled by the abstract class that it extends.
> 
> I'm a bit confused by how the auth header validation works. So I see that it goes into this method, which just ends up calling `auth.validateHttpHeader()`:
> 
> ```
> protected Future<Boolean> validateRequestAuthorization(HttpServerRequest req) throws Exception {
>     return auth.validateHttpHeader(() -> req.getHeader(HttpHeaders.AUTHORIZATION));
> }
> ```
> 
> But my understanding is that `AuthManager` is for user authentication, not JMX authentication, and authenticated handlers authenticate the JMX connection. So how come it's a method in `AuthManager` that is used to validate the header?
> 

`AbstractAuthenticatedRequestHandler` does both user auth and JMX auth - `validateRequestAuthorization` checks the `Authorization` header of the request and (by delegating to `AuthManager`) authenticates the user. `getConnectionDescriptorFromContext` checks the `X-JMX-Authorization` header of the request and parses out the JMX credentials, if any, including them in the returned `ConnectionDescriptor` which the handler then passes to the `TargetConnectionManager` to open a JMX connection, implicitly authenticating to the target JVM over the JMX connection.

> The problem I ran into is that with JMX auth enabled, but not user auth, `POST /api/v1/auth` always returned a `200` regardless of request headers, since the validation check just went to the `NoopAuthManager`.
> 

I see why that could be confusing, but that's to be expected. JMX auth can only be verified when ContainerJFR attempts to open a JMX connection to a specific target JVM, and on `/api/v1/auth` request there is no target - so there is no JMX authentication to check. Only user authentication can be performed. Since you disabled user auth, it will always succeed, because all users are authenticated to access ContainerJFR. This does not mean that all users have access to all targets that ContainerJFR can see/reach, however.

> > I think StaticAssets/WebClientAssets make sense to document as a wildcard so that it's clear what happens when a request is made to a path that isn't otherwise listed in the document.
> 
> Ah, I wasn't really sure what they are for, but I see now.
> 
> Both handlers are invoked when an invalid request is made, but I don't totally get how they work, so is there one I should use over the other in the doc to represent both? Is there one that is more like a "helper" handler and one that is more of a main handler?

`StaticAssetsGetHandler` is used for the case when a client requests something like `http://containerjfr/app.css` or `http://containerjfr/app.bundle.js` - paths that are not defined by any other handler, but correspond to filesystem contents.

`WebClientAssetsGetHandler` catches requests that the `StaticAssetsGetHandler` even misses, including simply `/`, but also any web-client in-app paths like `http://containerjfr/recordings/create`. In this case, ContainerJFR simply sends the client the `index.html` of the web-client, assuming that this is a browser and that the user is trying to get to the graphical frontend.

> 
> And should I be able to see a webpage if I do `curl ... --output foo.html` and then `google-chrome foo.html`? I see that the output is a HTML file, but I just get a blank page when I open it in a browser. So I'm not really sure how I should describe the output in the doc. But it looks like it should be something like a simple page just saying "ContainerJFR"?
> 
> Is this the correct output?

Probably. The web-client is not a simple static HTML page, there are other linked assets like the `app.bundle.js` which the React application is compiled down to. If you simply curl the HTML and then open that in a browser, the browser will try and fail to retrieve those other assets and you'll likely just see a broken HTML page with no real contents.

> 
> ```
> <!doctype html><html lang="en-US"><head><meta charset="utf-8"><title>ContainerJFR</title><meta id="appName" name="application-name" content="ContainerJFR"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/png" href="https://www.patternfly.org/components/patternfly/dist/img/favicon.ico"><base href="/"><link href="app.css" rel="stylesheet"></head><body><noscript>Enabling JavaScript is required to run this app.</noscript><div id="root"></div><script src="app.bundle.js"></script></body></html>
> ```

That looks about right.
