### ISSUE TITLE
Having Trouble Running `run.sh`

### ISSUE THREAD

**Issue by vic-ma** [rh-jmc-team/container-jfr#259]
I've been having trouble running `run.sh` for a while. I thought maybe after some time it would fix itself, but it looks like that's not the case. It's definitely on my end though, since commits where it was previously working no longer work for me.

```
[vma@victor-work ~/upstream-cjfr]$ ./run.sh
...
+ podman run --pod container-jfr --mount type=tmpfs,target=/flightrecordings --mount type=tmpfs,target=/templates --mount type=bind,source=/home/vma/upstream-cjfr/truststore,destination=/truststore,relabel=shared,bind-propagation=shared -p 9091:9091 -p 9090:9090 -p 8181:8181 -e CONTAINER_JFR_DISABLE_SSL= -e CONTAINER_JFR_DISABLE_JMX_AUTH= -e CONTAINER_JFR_LOG_LEVEL=ALL -e CONTAINER_JFR_RJMX_USER= -e CONTAINER_JFR_RJMX_PASS= -e CONTAINER_JFR_RJMX_PORT=9091 -e CONTAINER_JFR_CORS_ORIGIN= -e CONTAINER_JFR_WEB_HOST=0.0.0.0 -e CONTAINER_JFR_WEB_PORT=8181 -e CONTAINER_JFR_EXT_WEB_PORT=8181 -e CONTAINER_JFR_LISTEN_HOST=0.0.0.0 -e CONTAINER_JFR_LISTEN_PORT=9090 -e CONTAINER_JFR_EXT_LISTEN_PORT=9090 -e CONTAINER_JFR_AUTH_MANAGER=com.redhat.rhjmc.containerjfr.net.NoopAuthManager -e CONTAINER_JFR_ARCHIVE_PATH=/flightrecordings -e CONTAINER_JFR_TEMPLATE_PATH=/templates -e GRAFANA_DATASOURCE_URL=http://localhost:8080 -e GRAFANA_DASHBOARD_URL=http://localhost:3000/d/CazTnbSMz/ -e USE_LOW_MEM_PRESSURE_STREAMING= -e KEYSTORE_PATH= -e KEYSTORE_PASS= -e KEY_PATH= -e CERT_PATH= --rm -it quay.io/rh-jmc-team/container-jfr:latest
Error: invalid config provided: published or exposed ports must be defined when the pod is created: network cannot be configured when it is shared with a pod
+ cleanup
...
```

The only thing I can think of that has changed is my podman version (through normal fedora updates). With podman 2.0.5, it was not working, and right now I just updated to 2.0.6, which is also not working. From IRC logs, 2.0.2 was definitely working. I think 2.0.5 is the one where it broke, but I'm not sure.

I haven't been able to find older `2.x.x` versions of podman in the fedora repos or elsewhere online so I'm not able to downgrade to test if the podman version is indeed the problem.

`podman ps` and `podman pod list` both return empty.

Integration tests seem to work fine.

**Comment by andrewazores** [comment]
Interesting - @Alexjsenn just told me he's having the same issue currently. I'm on 2.0.4 and don't seemingly have any problems right now.

What if you try wiping out your containers state? I've had weird issues in the past when somehow bad state is left behind.

`rm -rf $HOME/.config/containers $HOME/.local/share/containers`

This will obviously delete all of your container images, pods/containers, etc., so don't do it if you have anything you need to preserve.

**Comment by vic-ma** [comment]
Moving the folder to somewhere else should also work right? I did that and I get the same error.

**Comment by andrewazores** [comment]
Yea, that should work too.

I'm hesitant to update it myself to see if I can reproduce it, at least until I can find a mirror for a known-working package version.

Anyway - from the error message it sounds like maybe the fix is to remove the `-p` flags from the `podman run` invocation and move them instead to `--publish` flags on the `podman pod create`?

**Comment by vic-ma** [comment]
If I do this, I don't get the error anymore and the container runs, but I get `Empty reply from server` if I try to curl cjfr with any of the HTTP API. I'm not sure if maybe this is an unrelated problem.

**Comment by andrewazores** [comment]
Hmm. What if you leave the flags there on the `run` but also add them on to the `create`? I haven't read the docs to see what the exact expected behaviour is when configuring networking on the pod vs on its containers.

Anyway,

https://koji.fedoraproject.org/koji/buildinfo?buildID=1573725

and

https://koji.fedoraproject.org/koji/buildinfo?buildID=1573726

are `2.0.4` for F31/F32, so you can also try downgrading and see if that fixes the problem and then we know for sure that it's a podman version problem.

**Comment by vic-ma** [comment]
Ah, so the empty reply problem was just because I didn't realize CJFR enables SSL by default now, so I was just running my usual curl commands, and I'd imagine it's normal to get an empty reply that way.

With podman `2.0.4`, `run.sh` works without any changes to the flags, so it looks like that invalid config problem did only start after `2.0.5`.

**Comment by andrewazores** [comment]
Good to know. I'll upgrade myself to `2.0.5+` and see if I can make `run.sh` work with it, since now we've confirmed `2.0.4` is safe and we have an easy downgrade path.
