### ISSUE TITLE
Recording summary reports show as plain text

### ISSUE THREAD

**Issue by tabjy** [rh-jmc-team/container-jfr#35]
This `Content-Type` response header for `/reports/<recording>` endpoint has incorrect value: `text/plain`.

![screenshot](https://i.imgur.com/eh6JL8T.png)

This problem is reproducible by running `kube-setup.sh` against a fresh Openshift installation. Looking at the script content, it's fetching the `latest` of `quay.io/rh-jmc-team/container-jfr`, which is currently `v0.4.3`

Interestingly, it appears the response content type is [explicitly set to `NanoHTTPD.MIME_HTML`](https://github.com/rh-jmc-team/container-jfr/commit/99c6305ec6d8a030720198b439e055d99b8cc4f6) since `v0.3.2`.

It's possible that Openshift's reverse proxy somehow overwrote this header field.

```
$ curl --head -H "Accept: text/html" http://container-jfr-container-jfr.10.15.17.89.nip.io/reports/test
HTTP/1.1 200 OK 
Content-Type: text/plain; charset=UTF-8
Date: Wed, 2 Oct 2019 19:33:32 GMT
Access-Control-Allow-Origin: *
Content-Length: 122387
Set-Cookie: 98c81825faae9a2f4c5de3ce34beb5a5=160b9b5980b10c3e9837d7d18ffece6b; path=/; HttpOnly
Cache-control: private

```

**Comment by andrewazores** [comment]
Thanks for the report. I haven't seen this before so I'm looking to reproduce it now.

**Comment by andrewazores** [comment]
Hmm. I tried to reproduce this using both the `kube-setup.sh` script as well as using the Minishift setup in https://github.com/rh-jmc-team/jmc-robots-demo, and in both cases the report is rendered as HTML as expected, and checking the response headers with cURL shows text/html as well. What kind of Openshift deployment are you using? Proxy rewriting of the response sounds maybe plausible?

**Comment by tabjy** [comment]
I'm using OpenShift Origin (or, OKD). The cluster is setup with `oc cluster up`, where the `oc` command is provided by the `origin-clients-3.11.1-1.fc30.x86_64` package on Fedora.

```
$ oc version 
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

I'll try to `docker exec` into the actual container and see what the response is before any kind of proxy.

**Comment by tabjy** [comment]
The following is executed directly inside the container:
```
$ busybox wget -S -O - localhost:8181/reports/test
Connecting to localhost:8181 (127.0.0.1:8181)
  HTTP/1.1 200 OK 
  Content-Type: text/plain; charset=UTF-8
  Date: Thu, 3 Oct 2019 16:23:39 GMT
  Access-Control-Allow-Origin: *
  Connection: close
  Content-Length: 122357
  
<!--
   Copyright (c) 2018, Oracle and/or its affiliates. All rights reserved.
   Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
-->
...
```

It's still `text/plain`. I have no idea what's happening...

**Comment by andrewazores** [comment]
Can you double check the image hash? The latest should be `sha256:0afea49f6cd34f09e753a2a1f4014576aa4ee3c6a92135bd5a7d8b7b6675c8fc`, which you can see via `docker inspect` and probably somehow with `oc` as well.

**Comment by tabjy** [comment]
The `kube-setup.sh` on my fork is outdated and is still pulling from `quay.io/andrewazores`. Sorry...

I'm closing this issue. I'm really sorry for the confusion.
