### ISSUE TITLE
Verify minimal set of JVM flags for remote JMX connection

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#4]
The documentation and all demos/examples currently state this list of JVM flags as required for `container-jfr` to be able to connect and manage targets:

```
    '-Dcom.sun.management.jmxremote.rmi.port=9091',
    '-Dcom.sun.management.jmxremote=true',
    '-Dcom.sun.management.jmxremote.port=9091',
    '-Dcom.sun.management.jmxremote.ssl=false',
    '-Dcom.sun.management.jmxremote.authenticate=false',
    '-Dcom.sun.management.jmxremote.local.only=false',
    '-Djava.rmi.server.hostname=$TARGET_HOSTNAME'
```

This set of flags should be examined to see if any are unnecessary or redundant.

**Comment by tabjy** [comment]
So I did some research and experiments. The minimal set of flags appears to be just:
```
-Dcom.sun.management.jmxremote.port=9091 \
-Dcom.sun.management.jmxremote.ssl=false \
-Dcom.sun.management.jmxremote.authenticate=false 
```

### Method of testing
1. run `kube-setup.sh` to set up a demo openshift project
2. create a simple target application
  ```
  oc new-app quay.io/rh-jmc-team/hot-methods:1 --name=hot-methods-1
  ```
3. adjust target application's flags and wait until the newly created pod is up
  ```
  oc set env dc/hot-methods-1 JAVA_OPTS="<flag set here>"
  ```
4. rescan, connect, and start a recording using web front-end to see if new flags work
5. meanwhile, keep an eye on websocket message frames to spot any errors
6. go back to step 3 and try with different flags

### Unnecessary properties

#### `com.sun.management.jmxremote.rmi.port`

According to [Marcus' blog](http://hirt.se/blog/?p=289), this property is often used with `com.sun.management.jmxremote.port`, and controls the port for the RMI registry. Without assigning a port here, a random free port will be chosen. It's often set to be the same as `com.sun.management.jmxremote.port` to simplify the process of JMX tunneling, but we don't really need it for this application.

#### `com.sun.management.jmxremote`

By defining this properly, regardless of what value it is (in fact, the value could just be empty), JXM is enabled. However, by setting `com.sun.management.jmxremote.port`, JMX is already [implicitly enabled](https://docs.oracle.com/javase/9/management/monitoring-and-management-using-jmx-technology.htm#JSMGM-GUID-2C1922AD-4BA0-4397-A3FE-7823F42A94A3).

#### `com.sun.management.jmxremote.local.only`

[By default](http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/jdk.management.agent/share/conf/management.properties#l70) this property is `true`. I made three attempts: setting it to `true`, setting it to `false`, and omitting setting it. In all three cases, discovering, connecting, and recording all work. I'm unsure why connecting from another pod, which are technically from other hosts, can connect the target even if `local.only` is set to true, but this flag seem to be redundant.

#### `java.rmi.server.hostname`

[As documented](https://docs.oracle.com/javase/8/docs/technotes/guides/rmi/javarmiproperties.html), the default value of this property is the IP address of the local host, in "dotted-quad" format.

If this property is unset, or set to the actual application name, all functions work properly. However, while set to an unresolvable hostname, `java.net.UnknownHostException: test-hostname` exception occurs when connecting. (Discovery still works, and interestingly, the argument of `connect` command is the valid ip address, not the hostname.)

This flag offers no fine-grained controls, as it must be set to the application name, and it introduces confusions and complexity. Therefore, it should not be explicitly set.

In addition, the value of this property doesn't affects the UI in the *Target JVM* drop-down. In my case, the display is always `hot-methods-1.container-jfr.svc.cluster.local:9091`.

### Necessary properties

#### `com.sun.management.jmxremote.port`

Must be `9091`. It enables JMX, and container-jfr expects it on port 9091.

#### `com.sun.management.jmxremote.ssl`

Must be `false`. As #5 is closed in favour of #9 and #10, container-jfr doesn't support encryption on JMX connections. Also, pods are running in an isolated subnet, security is most likely not a concern as long as the service ports are not exposed.

#### `com.sun.management.jmxremote.authenticate`

Must be `false`. For the same reason above.

**Comment by andrewazores** [comment]
@tabjy thank you for the excellent and detailed investigation. Could you open a PR to update the documentation with your findings? `container-jfr`'s own flags (set in `build.gradle`) could also be reduced to this minimal set.

**Comment by tabjy** [comment]
@andrewazores No problem. See #34. Thanks!
