### ISSUE TITLE
JFR files should be re-uploadable into storage

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#55]
Users should be able to (re-)upload existing JFR files from their local machine into ContainerJFR's storage (archive).

1) In case their ContainerJFR instance goes away and storage is lost (ex. OpenShift Operator is deleted and restored)

2) To allow ContainerJFR to be used as a desktop application for analysis, but with the Flight Recorder options set by JVM flags and dumped to local file directly by the JVM or another external tool (ex. jcmd)

3) To allow migration between different local environments, for example a user using ContainerJFR as a desktop application with a workstation and a laptop

4) For simply restoring accidentally deleted recordings from ContainerJFR archives

ContainerJFR should do some validation that the received file is a valid JFR file, that the specified name for the file is acceptable (ie. compatible with file-relating commands), etc. The file name should also be automatically updated if the specified name conflicts with a pre-existing file name, so that the upload doesn't overwrite previous data.

**Comment by tabjy** [comment]
@andrewazores If this issue is not work-in-progress, could please assign it to me? Thanks!

**Comment by andrewazores** [comment]
@tabjy sure, thanks
