### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#64]
Some unit tests are failing since #57 , and I overlooked this before merging the PR. @tabjy , please correct them.

**Comment by tabjy** [comment]
Could you elaborate on which tests are failing? 

Currently, I have three failing tests on my side, namely,
- com.redhat.rhjmc.containerjfr.commands.internal.SaveRecordingCommandTest > shouldExecuteAndSaveRecordingWithExtension() FAILED

- com.redhat.rhjmc.containerjfr.commands.internal.SaveRecordingCommandTest > shouldExecuteAndSaveRecording() FAILED

- com.redhat.rhjmc.containerjfr.commands.internal.SaveRecordingCommandTest > shouldExecuteAndSaveRecordingAndReturnSerializedSuccess() FAILED

These failures are reproducible for commit 09af899, before #57.

**Comment by andrewazores** [comment]
You might be right and I wouldn't be surprised. I'll take another look when I'm back at my workstation. Thanks.




---- On Wed, 06 Nov 2019 13:10:28 -0800 notifications@github.com wrote ----



Could you elaborate on which tests are failing?

Currently, I have three failing tests on my side, namely,

com.redhat.rhjmc.containerjfr.commands.internal.SaveRecordingCommandTest > shouldExecuteAndSaveRecordingWithExtension() FAILED

com.redhat.rhjmc.containerjfr.commands.internal.SaveRecordingCommandTest > shouldExecuteAndSaveRecording() FAILED

com.redhat.rhjmc.containerjfr.commands.internal.SaveRecordingCommandTest > shouldExecuteAndSaveRecordingAndReturnSerializedSuccess() FAILED

These failures are reproducible for commit 09af899, before #57.
