### ISSUE TITLE
Should minimal mode respond 200 on grafana_dashboard_url and grafana_datasource_url ?

### ISSUE THREAD

**Issue by andrewazores** [rh-jmc-team/container-jfr#84]
When running in minimal mode and with the Grafana and jfr-datasource environment variables unset, the endpoints /grafana_dashboard_url and /grafana_datasource_url respond 200 and with an empty string in the JSON response value. Should this instead be a 404 or other error status?

**Comment by tabjy** [comment]
IMHO, the status code should be `5xx` server error indicating such feature is unavailable because it's disabled/non-existent. 

I think either `501 Not Implemented` or `503 Service Unavailable` is more suitable than `404 Not Found`. However, since `503` often suggests the services will potentially be available after a while, I would prefer `501`.

**Comment by andrewazores** [comment]
Hmm. Docs I can find detailing 501 say it's typically used when the server doesn't understand the request method, which isn't quite what we need to convey. I also see things like "and is incapable of supporting it (the request method) for any resource", which is not true here.

503's temporary nature might be acceptable though. The deployment could be respun into a non-minimal state, or perhaps the client request happened to come in at a time when the admin had spun up the service but not yet finished manually linking up the components and setting the env vars. But, 503 is also potentially misleading, because this typically indicates that the entire service is unavailable. Here, we're simply stating that a specific capability is disabled, but the service itself is definitely available.

**Comment by tabjy** [comment]
Yah that makes sense. 

Another option is to respond with a generic `500`, as well as a message stating it's available in minimal mode.
